import type { Metadata } from "next";
import localFont from "next/font/local";

import {Plus_Jakarta_Sans}  from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ui/theme-provider";

const fontSans=Plus_Jakarta_Sans({
   //weight:["800"],
   weight:["200","300", "400", "500", "600", "700"],
  subsets:["latin"],
  variable:"--font-sans",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen  font-sans bg-dark-300 antialiased remove-scrollbar",fontSans.variable)}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        
      </body>
    </html>
  );
}
